# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('fog', ['core', 'internet', 'config-store','stats', 'point-to-point', 'mobility'])
    module.source = [
        'model/my-onoff-application.cc',
        'model/my-tcp-server.cc',
        'model/my-receive-server.cc',
        'model/my-queue-item.cc',
        'model/my-tree.cc',
        'model/my-orchestrator.cc',
        'helper/my-onoff-application-helper.cc',
        'helper/my-tcp-server-helper.cc',
        'helper/my-receive-server-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('fog')
    module_test.source = [
        'test/fog-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'fog'
    headers.source = [
        'model/my-onoff-application.h',
        'model/my-tcp-server.h',
        'model/my-receive-server.h',
        'model/my-queue-item.h',
        'model/my-tree.h',
        'model/my-orchestrator.h',
        'helper/my-onoff-application-helper.cc',
        'helper/my-onoff-application-helper.h',
        'helper/my-tcp-server-helper.h',
        'helper/my-receive-server-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

